[package]
name = "contract-generation"
version = "0.2.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0.0", features = ["abigen", "rustls", "ws", "ethers-solc"] }
tokio = { version = "0.2", features = ["macros"] }
eyre = "0.6"
serde_json = "1.0"