apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: function-simulator-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi # Adjust the size as needed
