apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-server
  labels:
    app: secrets-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: secrets-server
        should_scrape: scrape
    spec:
      containers:
        - name: secrets-server
          image: {{ .Values.image }}
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: {{ .Values.databaseUrl }}
          ports:
            - name: websocket
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 512Mi
              cpu: 500m
              # sgx.intel.com/epc: 10485760
