name: Release App

on:
  workflow_dispatch:
    inputs:
      app:
        type: choice
        required: true
        description: The app to release to 'latest' docker tag
        options:
          - function-simulator
          - secrets-server

jobs:
  release_app:
    name: "Push App to Dockerhub 'latest' Tag"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_CI_USERNAME }}
          password: ${{ secrets.DOCKERHUB_CI_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "switchboardlabs/default"

      - name: Set up tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: switchboardlabs/${{ github.event.inputs.app }}
          tags: |
            type=raw,value=latest,enable=true
          labels: |
            org.opencontainers.image.vendor=SwitchboardLabs

      - name: Set Anchor Version
        if: ${{ github.event.inputs.app == 'function-simulator' }}
        working-directory: rust/switchboard-solana
        run: ./set-anchor.sh 27

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: "./apps/${{ github.event.inputs.app }}/Dockerfile"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from:
            type=registry,ref=switchboardlabs/${{ github.event.inputs.app
            }}:buildcache
          cache-to:
            type=registry,ref=switchboardlabs/${{ github.event.inputs.app
            }}:buildcache,mode=max
