import dotenv from "dotenv";

dotenv.config();

export function logEnv(): void {
  ENV_VARIABLES.map((e) => {
    if (
      e in process.env &&
      process.env[e] !== undefined &&
      process.env[e] !== null
    ) {
      console.info(`${e}='${process.env[e]}'`);
    }
  });
}

export const ENV_VARIABLES = [
  "GCP_CONFIG_BUCKET",
  "AWS_CONFIG_BUCKET",
  "TASK_RUNNER_SOLANA_RPC",
  "METRICS_EXPORTER",
  "PAGERDUTY_EVENT_KEY",
  "VERBOSE",
  "DEBUG",
  "CHAIN",
  "HEARTBEAT_INTERVAL",

  // keypair
  "PAYER_SECRET_PATH",
  "FS_PAYER_SECRET_PATH",
  "APTOS_FS_PAYER_SECRET_PATH",
  "NEAR_FS_PAYER_SECRET_PATH",
  "SOLANA_FS_PAYER_SECRET_PATH",
  "STARKNET_FS_PAYER_SECRET_PATH",
  "COREDAO_FS_PAYER_SECRET_PATH",
  "ARBITRUM_FS_PAYER_SECRET_PATH",

  "DOCKER_PAYER_SECRET",
  "APTOS_DOCKER_PAYER_SECRET",
  "NEAR_DOCKER_PAYER_SECRET",
  "SOLANA_DOCKER_PAYER_SECRET",
  "STARKNET_DOCKER_PAYER_SECRET",
  "COREDAO_DOCKER_PAYER_SECRET",
  "ARBITRUM_DOCKER_PAYER_SECRET",

  "GOOGLE_PAYER_SECRET_PATH",
  "APTOS_GOOGLE_PAYER_SECRET_PATH",
  "NEAR_GOOGLE_PAYER_SECRET_PATH",
  "SOLANA_GOOGLE_PAYER_SECRET_PATH",
  "STARKNET_GOOGLE_PAYER_SECRET_PATH",
  "COREDAO_GOOGLE_PAYER_SECRET_PATH",
  "ARBITRUM_GOOGLE_PAYER_SECRET_PATH",

  "AMAZON_PAYER_SECRET_PATH",
  "APTOS_AMAZON_PAYER_SECRET_PATH",
  "NEAR_AMAZON_PAYER_SECRET_PATH",
  "SOLANA_AMAZON_PAYER_SECRET_PATH",
  "STARKNET_AMAZON_PAYER_SECRET_PATH",
  "COREDAO_AMAZON_PAYER_SECRET_PATH",
  "ARBITRUM_AMAZON_PAYER_SECRET_PATH",

  "AMAZON_PAYER_SECRET_NAME",
  "AWS_SECRET_NAME",

  // solana
  "SOLANA_CLUSTER",
  "CLUSTER",
  "RPC_URL",
  "WS_URL",
  "SOLANA_BACKUP_MAINNET_RPC",
  "BACKUP_MAINNET_RPC",
  "SOLANA_ORACLE_KEY",
  "ORACLE_KEY",
  "SOLANA_UNWRAP_STAKE_THRESHOLD",
  "UNWRAP_STAKE_THRESHOLD",
  "ENABLE_DATA_FEED_NONCE",
  "SOLANA_ENABLE_DATA_FEED_NONCE",
  "SOLANA_NONCE_QUEUE_SIZE",
  "NONCE_QUEUE_SIZE",

  // near
  "NEAR_NETWORK_ID",
  "NEAR_RPC_URL",
  "NEAR_ORACLE_KEY",
  "NEAR_NAMED_ACCOUNT",

  // evm (coredao)
  "EVM_CONTRACT_ADDRESS",
  "EVM_RPC_URL",
  "EVM_ORACLE_KEY",
  "EVM_CHAIN_ID",

  // aptos
  "APTOS_PID",
  "APTOS_RPC_URL",
  "APTOS_ORACLE_KEY",
  "APTOS_CRANK_KEY",

  // starknet
  "STARKNET_PID",
  "STARKNET_NETWORK_ID",
  "STARKNET_RPC_URL",
  "STARKNET_PAYER_ADDRESS",
  "STARKNET_ORACLE_KEY",
  "STARKNET_CRANK_KEY",
];
